"""empty message

Revision ID: e5cde517174f
Revises: 228170eed859
Create Date: 2022-04-07 00:07:24.502862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cde517174f'
down_revision = '228170eed859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_user_id_key', 'favorite', type_='unique')
    op.drop_constraint('ingredient_drink_name_key', 'ingredient', type_='unique')
    op.drop_constraint('ingredient_ingredient_name_key', 'ingredient', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ingredient_ingredient_name_key', 'ingredient', ['ingredient_name'])
    op.create_unique_constraint('ingredient_drink_name_key', 'ingredient', ['drink_name'])
    op.create_unique_constraint('favorite_user_id_key', 'favorite', ['user_id'])
    # ### end Alembic commands ###
