"""empty message

Revision ID: f69dd173be8d
Revises: e5cde517174f
Create Date: 2022-04-09 00:11:41.120594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69dd173be8d'
down_revision = 'e5cde517174f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_drink_id_key', 'ingredient', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ingredient_drink_id_key', 'ingredient', ['drink_id'])
    # ### end Alembic commands ###
